version: '3.8'

services:
  bff-biblioteca:
    image: bcortes1013/bff-biblioteca:latest
    container_name: bff_app
    ports:
      - "80:8080"
    environment:
      - AZURE_FUNCTIONS_URL=https://api-biblioteca-grupo11.azurewebsites.net/api/
    restart: always