-- USUARIOS
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR2(12) UNIQUE NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    fecha_registro DATE DEFAULT SYSDATE
);

-- PRESTAMOS
CREATE TABLE prestamos (
    id_prestamo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    isbn_libro VARCHAR2(20) NOT NULL,
    titulo_libro VARCHAR2(150) NOT NULL,
    fecha_prestamo DATE DEFAULT SYSDATE,
    fecha_devolucion DATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO',
    CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

-- Datos de prueba
INSERT INTO usuarios (rut, nombre, email) VALUES ('11222333-4', 'Juan Perez', 'juan@correo.cl');
COMMIT;