# Etapa 1: Construcción (Usa un contenedor temporal con Maven y Java 21)
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
# Copiamos el pom.xml y el código fuente al contenedor
COPY pom.xml .
COPY src ./src
# Compilamos el proyecto DENTRO de Docker
RUN mvn clean package -DskipTests

# Etapa 2: Ejecución (Contenedor final ligero para Azure)
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
# Rescatamos el .jar generado en la Etapa 1
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]