spring.application.name=bff-app

# 1. Base de datos falsa en memoria (H2) para engañar a Spring Boot
spring.datasource.url=jdbc:h2:mem:fakedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

# 2. URL de las Azure Functions (El único puente que realmente usaremos)
azure.functions.url=${AZURE_FUNCTIONS_URL:https://api-biblioteca-grupo11.azurewebsites.net/api/}