spring.application.name=bff-app

# 1. Conexión a la Base de Datos Oracle
# Usamos variables de entorno (que inyecta el docker-compose). 
# Lo que está después de los dos puntos (:) es el valor por defecto si lo corres localmente en tu IDE.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:BIBLIO_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:BiblioPass123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. Configuración de JPA / Hibernate
# Ponemos "none" porque nuestro init.sql ya se encarga de crear las tablas.
spring.jpa.hibernate.ddl-auto=none
# Esto te servirá para ver las consultas SQL en la consola (ideal para depurar mañana con Ignacio)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. URL de las Azure Functions (FaaS)
# Aquí también usamos variable de entorno para que sea fácil cambiarla al subir a Docker Lab
azure.functions.url=${AZURE_FUNCTIONS_URL:http://localhost:7071/api/}